[project]
name = "local-navier-stokes"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.24.0",
    "matplotlib>=3.6.0",
    "jupyter>=1.0.0",
    "scipy>=1.10.0",
    "pandas>=2.3.1",
]
